name: Automated Vote

on:
  schedule:
    - cron: '0/5 \* \* \* \*  # Run every 5 minutes (adjust as needed)

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python vote.py  # Replace with your script file name
